server:
  port: 8080
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gmeza-nttdata/bootcamp-config-data.git
          default-label: acr
