server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**
        - id: credit-service
          uri: lb://CREDIT-SERVICE
          predicates:
            - Path=/credits/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: operation-service
          uri: lb://OPERATION-SERVICE
          predicates:
            - Path=/operations/**
