server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-dev:8761/eureka/
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**
        - id: credit-service
          uri: lb://CREDIT-SERVICE
          predicates:
            - Path=/credits/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: account-transaction-service
          uri: lb://ACCOUNT-TRANSACTION-SERVICE
          predicates:
            - Path=/account-transactions/**
        - id: credit-transaction-service
          uri: lb://CREDIT-TRANSACTION-SERVICE
          predicates:
            - Path=/credit-transactions/**
        - id: account-transfer-service
          uri: lb://ACCOUNT-TRANSFER-SERVICE
          predicates:
            - Path=/account-transfers/**
        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/reports/**