server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8081/users/
          predicates:
            - Path=/users/**
        - id: product-service
          uri: http://localhost:8082/accounts/
          predicates:
            - Path=/accounts/**
        - id: credit-service
          uri: http://localhost:8083/credits/
          predicates:
            - Path=/credits/**
