server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/project1
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

user:
  web:
    url: http://user-service/users

account:
  web:
    url: http://account-service/accounts

credit:
  web:
    url: http://credit-service/credits