server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://root:root@mongo-dev:27017/bootcamp

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-dev:8761/eureka/

user:
  web:
    url: http://user-service/users

account:
  web:
    url: http://account-service/accounts

credit:
  web:
    url: http://credit-service/credits