server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://root:root@mongo-dev:27017/bootcamp

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-dev:8761/eureka/

kafka:
  bootstrapAddress: host.docker.internal:9092
  groupId: group_id
  